### ISSUE TITLE
Discussion on the Directory Structure

### ISSUE THREAD

**Issue by rvk7895** [OSDG-IIITH/music-club-website#3] opened 2020-05-26 08:31 UTC
Can we decide upon what the structure of the directories would be. Like the name of folders that contain what component and stuff.

**Comment by Mehul1604** [comment] 2020-05-26 09:07
I have a pr pending which tells just that waiting for them to merge

**Comment by Tanvi141** [comment] 2020-06-04 05:45
Assuming the issue is resolved, I'll close it

**Closed by Tanvi141** 2020-06-04 05:45 UTC
